### ISSUE TITLE
Mobile App - 1.4.0 - Firebase Error

### ISSUE THREAD

**Issue by WillieSpence** [thingsboard/flutter_thingsboard_pe_app#200]
Hi,

I've upgraded the Mobile App to the 1.4.0 release, and I'm getting the following error on iOS. Anyone encountered this before? This happens after I entered my login credentials.

flutter:   DEBUG └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   ERROR ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   ERROR │ [firebase_messaging/unknown] An unknown error has occurred.
flutter:   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter:   ERROR │ #0   StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
flutter:   ERROR │ #1   MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
flutter:   ERROR │ #2   <asynchronous suspension>
flutter:   ERROR │ #3   MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:534:43)
flutter:   ERROR │ #4   <asynchronous suspension>
flutter:   ERROR │ #5   MethodChannelFirebaseMessaging.getToken (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:248:11)
flutter:   ERROR │ #6   <asynchronous suspension>
flutter:   ERROR │ #7   NotificationService.getToken (package:thingsboard_app/utils/services/notification_service.dart:100:17)
flutter:   ERROR ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter:   ERROR │ ⛔ TbContext.onUserLoaded: [firebase_messaging/unknown] An unknown error has occurred.
flutter:   ERROR └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Regards

**Comment by WillieSpence** [comment]
This seems to be only issue on iOS. Android works fine.

**Comment by WillieSpence** [comment]
My mistake. Had to update my dependencies and clean build the project which resolved the issue

fvm flutter pub upgrade
