### ISSUE TITLE
Time window setting layout has problem in iPhone 13

### ISSUE THREAD

**Issue by jjksam** [thingsboard/flutter_thingsboard_pe_app#47]
![WechatIMG235](https://github.com/thingsboard/flutter_thingsboard_pe_app/assets/1285799/3208a6ab-aa0b-4f73-8303-f1dafbed770d)
Time window setting layout problem with master branch code compile and run on iPhone 13.

**Comment by jjksam** [comment]
Same problem (web component layout problem) exists in thingsboard.cloud web in iPhone 13.
![WechatIMG236](https://github.com/thingsboard/flutter_thingsboard_pe_app/assets/1285799/17600e1c-d04d-4d5f-a12a-59d02be55108)

**Comment by holgerkoch** [comment]
Hi,

after update ThingsBoard PE to 3.5.1, we must rebuild the app, because changes of the api. 
Unfortunatelly, since them we have also the layout problems.

Did anybody found a solution for this or had a tipp for us, how can we solve it?

Best regards, Holger

<img width="327" alt="Android_2-20230616-115836" src="https://github.com/thingsboard/flutter_thingsboard_pe_app/assets/3931187/1656b763-81a5-4c82-8abf-53c91665b185">

![iPhone_2-20230616-115840](https://github.com/thingsboard/flutter_thingsboard_pe_app/assets/3931187/64cc704e-a732-4601-b68f-8c90b3007047)

**Comment by julianwuensche** [comment]
Hello,
we have the same problems. Both in the display on Andoid and iOS. As you can see in the picture. In addition, the dashboards in Android do not load at all and there is an error or exception in the logs. Does anyone else have these problems with Android?
![image](https://github.com/thingsboard/flutter_thingsboard_pe_app/assets/137515366/a99e8439-dc64-48f9-8476-fb83c536e48a)

Android exception:
`E/System  ( 4436): Uncaught exception thrown by finalizer
E/System  ( 4436): java.lang.IllegalStateException: Warning: Router objects should be explicitly closed when no longer required otherwise you may leak handles.
E/System  ( 4436): 	at II.finalize(chromium-SystemWebView.apk-default-410412053:4)
E/System  ( 4436): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
E/System  ( 4436): 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
E/System  ( 4436): 	at java.lang.Daemons$Daemon.run(Daemons.java:139)
E/System  ( 4436): 	at java.lang.Thread.run(Thread.java:923)
E/System  ( 4436): Caused by: java.lang.Exception: AutocloseableRouter allocated at:
E/System  ( 4436): 	at II.<init>(chromium-SystemWebView.apk-default-410412053:7)
E/System  ( 4436): 	at tL.<init>(chromium-SystemWebView.apk-default-410412053:6)
E/System  ( 4436): 	at org.chromium.content.browser.framehost.RenderFrameHostImpl.<init>(chromium-SystemWebView.apk-default-410412053:10)
E/System  ( 4436): 	at org.chromium.content.browser.framehost.RenderFrameHostImpl.create(chromium-SystemWebView.apk-default-410412053:1)
E/System  ( 4436): 	at J.N.MjidYpBx(Native Method)
E/System  ( 4436): 	at org.chromium.content.browser.webcontents.WebContentsImpl.M(chromium-SystemWebView.apk-default-410412053:3)
E/System  ( 4436): 	at T8.g(chromium-SystemWebView.apk-default-410412053:5)
E/System  ( 4436): 	at com.android.webview.chromium.WebViewChromium.postMessageToMainFrame(chromium-SystemWebView.apk-default-410412053:4)
E/System  ( 4436): 	at android.webkit.WebView.postWebMessage(WebView.java:1971)
E/System  ( 4436): 	at androidx.webkit.internal.ApiHelperForM.postWebMessage(ApiHelperForM.java:172)
E/System  ( 4436): 	at androidx.webkit.WebViewCompat.postWebMessage(WebViewCompat.java:487)
E/System  ( 4436): 	at com.pichillilorenzo.flutter_inappwebview.InAppWebViewMethodHandler.onMethodCall(InAppWebViewMethodHandler.java:568)
E/System  ( 4436): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/System  ( 4436): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/System  ( 4436): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/System  ( 4436): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/System  ( 4436): 	at android.os.Handler.handleCallback(Handler.java:938)
E/System  ( 4436): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/System  ( 4436): 	at android.os.Looper.loop(Looper.java:223)
E/System  ( 4436): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/System  ( 4436): 	at java.lang.reflect.Method.invoke(Native Method)
E/System  ( 4436): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/System  ( 4436): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`

**Comment by WillieSpence** [comment]
![Screenshot 2024-06-07 at 14 53 01](https://github.com/thingsboard/flutter_thingsboard_pe_app/assets/157971298/fa3e5f55-9fe7-4cc3-9af7-d69dd7a39ee6)

Same issue here. I have gone through the mobile app code, and it does seems like the issue is on the Web Component and not the Mobile App itself

**Comment by WillieSpence** [comment]
For those struggling with this, please check this [link](https://github.com/thingsboard/thingsboard/issues/8795) for a workaround.

**Comment by ybeshkarov** [comment]
It's true. This is an issue on the platform level and we need to wait until https://github.com/thingsboard/thingsboard/issues/8795 is resolved.
